baseURL = "https://rhoeijmakers.github.io/demos/"
languageCode = "en-us"
title = "Demo"
theme = "mixedpaper"
enableRobotsTXT = true
paginate = 3 # Set the number of posts to show before overflowing to the next page
pygmentsUseClasses = true
publishDir = "docs"

[taxonomies]
tag = "tags"

# Menu links along the sidebar navigation.
[[menu.main]]
identifier = "about"
name = "About"
url = "about/"
weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "tags/"
weight = 2

